//
//  NotificationConstants.swift
//  Lafro
//
//  Created by ArashHome on 19/01/15.
//  Copyright (c) 2015 Arash K. All rights reserved.
//

import Foundation

var NOTIF_TRANSACTIONS_UPDATED: String = "NOTIFICATION_TRANSACTIONS_UPDATED"



var NOTIF_USER_INFO_UPDATED_TRANSACTIONS: String = "USER_INFO_UPDATED_TRANSACTIONS"


var NOTIF_REACHABILITY_CHANGE_WIFI: String = "REACHABILITY_CHANGE_WIFI"
var NOTIF_REACHABILITY_CHANGE_WWLAN: String = "REACHABILITY_CHANGE_WWLAN"
var NOTIF_REACHABILITY_CHANGE_NO_CONNECTION: String = "REACHABILITY_CHANGE_NO_CONNECTION"
